package Enums;

public enum Boletas {
    ALIANZA_LA_LIBERTAD_AVANZA,
    PARTIDO_NUEVO_BUENOS_AIRES,
    LIBER_AR,
    FRENTE_DE_IZQUIERDA_UNIDAD,
    FRENTE_PATRIOTA_FEDERAL,
    UNION_LIBERAL,
    ALIANZA_FUERZA_PATRIA,
    COALICION_CIVICA,
    MOVIMIENTO_POPULAR_SOCIAL_Y_CULTURAL_PROYECTO_SUR,
    PROPUESTA_FEDERAL_PARA_EL_CAMBIO,
    ALIANZA_PROVINCIAS_UNIDAS,
    ALIANZA_POTENCIA,
    ALIANZA_UNION_FEDERAL,
    ALIANZA_NUEVOS_AIRES,
    MOVIMIENTO_AVANZADA_SOCIALISTA;

}
