package Enums;

public enum Partidos {
    PARTIDO_NUEVO_BUENOS_AIRES,
    LIBER_AR,
    FUERZA_PATRIA,
    FRENTE_DE_IZQUIERDA_Y_DE_LOS_TRABAJADORES,
    FRENTE_PATRIOTA_FEDERAL,
    PARTIDO_DEMOCRATA_PROGRESISTA,
    UNION_LIBERAL,
    COALICION_CIVICA,
    PROYECTO_SUR,
    PROYECTO_FEDERAL_PARA_EL_CAMBIO,
    PROVINCIA_UNIDAS,
    PARTIDO_LIBERTARIO,
    POTENCIA,
    UNION_FEDERAL,
    NUEVOS_AIRES,
    MOVIMIENTO_AVANZADA_SOCIALISTA
}
